#!/bin/bash
#
# App Store Asset Preparation Script
# Generated by AppStorePrep - https://github.com/anthropics/appstore-prep
#
# Generates all App Store metadata, screenshots, and icons
# then optionally pushes to App Store Connect via EAS
#
# Usage:
#   ./scripts/prepare-appstore.sh           # Generate assets only
#   ./scripts/prepare-appstore.sh --push    # Generate and push to ASC
#   ./scripts/prepare-appstore.sh --text-only  # Text only (no images, faster)
#
# Configuration:
#   Option 1: Set OPENAI_API_KEY in .appstoreprep/config.env (local to project)
#   Option 2: Set OPENAI_API_KEY in ~/dev2/AppStorePrep/.env (shared)
#   Option 3: Set APPSTORE_PREP_DIR to custom location

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
LOCAL_CONFIG="$PROJECT_DIR/.appstoreprep/config.env"
APPSTORE_PREP_DIR="${APPSTORE_PREP_DIR:-$HOME/dev2/AppStorePrep}"

# Load local config if exists
if [ -f "$LOCAL_CONFIG" ]; then
    echo "📋 Loading local config from .appstoreprep/config.env"
    set -a
    source "$LOCAL_CONFIG"
    set +a
fi

echo "📱 App Store Asset Preparation"
echo "==============================="
echo "Project: Quento"
echo "Bundle ID: com.quento.app"
echo ""

# Check if AppStorePrep exists
if [ ! -d "$APPSTORE_PREP_DIR" ]; then
    echo "❌ Error: AppStorePrep not found at $APPSTORE_PREP_DIR"
    echo "   Set APPSTORE_PREP_DIR environment variable or install at default location"
    exit 1
fi

# Check if OpenAI API key is configured (local or in AppStorePrep)
if [ -z "$OPENAI_API_KEY" ] && [ ! -f "$APPSTORE_PREP_DIR/.env" ]; then
    echo "❌ Error: OpenAI API key not configured"
    echo "   Option 1: Copy .appstoreprep/config.env.example to config.env and add your key"
    echo "   Option 2: Create $APPSTORE_PREP_DIR/.env with OPENAI_API_KEY=..."
    exit 1
fi

# Install AppStorePrep dependencies if needed
if [ ! -d "$APPSTORE_PREP_DIR/node_modules" ]; then
    echo "📦 Installing AppStorePrep dependencies..."
    (cd "$APPSTORE_PREP_DIR" && npm install)
fi

# Parse arguments
EXTRA_ARGS=""
PUSH_AFTER=false

for arg in "$@"; do
    case $arg in
        --push)
            PUSH_AFTER=true
            ;;
        --text-only)
            EXTRA_ARGS="$EXTRA_ARGS --skip-screenshots --skip-icon"
            ;;
        *)
            EXTRA_ARGS="$EXTRA_ARGS $arg"
            ;;
    esac
done

# Run AppStorePrep with EAS integration
echo "🚀 Generating App Store assets..."
echo "   This may take 1-2 minutes for full generation"
echo ""

# Run from AppStorePrep directory so .env is loaded
(cd "$APPSTORE_PREP_DIR" && node src/index.js "$PROJECT_DIR" \
    --integrate \
    -o "$PROJECT_DIR/appstore-assets" \
    $EXTRA_ARGS)

echo ""

# Push to App Store Connect if requested
if [ "$PUSH_AFTER" = true ]; then
    echo "📤 Pushing metadata to App Store Connect..."
    echo ""

    if ! command -v eas &> /dev/null; then
        echo "❌ Error: EAS CLI not found"
        echo "   Install with: npm install -g eas-cli"
        exit 1
    fi

    (cd "$PROJECT_DIR" && eas metadata:push)

    echo ""
    echo "✅ Metadata pushed to App Store Connect!"
else
    echo "📋 Next steps:"
    echo "   1. Review: $PROJECT_DIR/eas-metadata/"
    echo "   2. Check: $PROJECT_DIR/store.config.json"
    echo "   3. Push: npm run appstore:push (or eas metadata:push)"
fi
